name: Check Code Formatting

on:
  pull_request:
    paths:
      - '**.c'
      - '**.h'
      - '**.cpp'
      - '**.hpp'
  push:
    branches:
      - master
    paths:
      - '**.c'
      - '**.h'
      - '**.cpp'
      - '**.hpp'

jobs:
  clang-format:
    name: clang-format
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: false

    - name: Run clang-format
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        echo -n "Checking coding style with clang-format..."
        fail=0
        while read -r i; do
            if ! clang-format-11 --Werror --dry-run "${i}" > /dev/null 2>&1;
            then
                if [ "${fail}" == "0" ]; then
                    echo "[FAIL]"
                    echo "::group::Suggested Fix-up Commands"
                fi
                fail=1
                echo "::warning file=${i}::Please run clang-format -i ${i}"
            fi
            if [ "${fail}" != "0" ]; then
                echo "::endgroup::"
            fi
        done < <(find NFIQ2 \( -name "*.c" -o -name "*.h" \
            -o -name "*.cpp" -o -name "*.hpp" \) -a \! -path '*wsq*' \
            -a \! -name 'RandomForestTrainedParams.h')
        if [ "${fail}" == "1" ]; then
            msg="Please run the above files through clang-format using the "
            msg+=".clang-format configuration and push your changes to the "
            msg+="same branch. See CONTRIBUTING.md for more information."
            echo "::error ::${msg}"
            exit 1
        else
            echo "[OKAY]"
        fi
